---
name: Data-CPAN-DSLIP-Explain
version: 0.03
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: '"decrypts" CPAN module DSLIP code'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
build_requires:
  Test::More: 0
provides:
  Data::CPAN::DSLIP::Explain:
    file: lib/Data/CPAN/DSLIP/Explain.pm
    version: 0.03
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
